//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayBookingWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayRequest
    {
        public int Id { get; set; }
        public int employee_id { get; set; }
        public System.DateTime date_from { get; set; }
        public System.DateTime date_to { get; set; }
        public string reason { get; set; }
        public Nullable<bool> approval { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
